### ISSUE TITLE
How did adjustment the gmail.db size?

### ISSUE THREAD

**Issue by ginoliang1130** [ant9000/gmailbackup#3]
Hi Developer,

The gmail.db file size maximum is 5GB. How did adjustment the file size?

Thanks.

**Comment by ant9000** [comment]
As far as I know, there is no such limit on SQLite (maximum DB size is 140TB, reported here: https://sqlite.org/limits.html).

It is much more likely that you have reached some limit on the filesystem where the database is saved, instead.

**Comment by ginoliang1130** [comment]
Thank you for your reply.
